// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sabsbhwpildojcfwbfei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhYnNiaHdwaWxkb2pjZndiZmVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzOTgzNTAsImV4cCI6MjA1Nzk3NDM1MH0.sIFmjw7mIPPgquNpwkQaBvW39Q4xRI_HoG6cCbCS88s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);